# otol - Open Tree of Life API

Citation: Smith, S.A., & Brown, J.W. (2018). Constructing a broadly inclusive seed plant phylogeny. American Journal of Botany, 105(3), 302-314.
"

Citation: Zuntini, A.R., Carruthers, T., Maurin, O. et al. (2024). Phylogenomics and the rise of the angiosperms. Nature 629, 843–850.
"ot_2304"
It covers nearly 8,000 genera (roughly 60% of all accepted angiosperm genera, representing >85% of species diversity) and is fossil dated.

In [1]:
import toytree
import numpy as np

In [2]:
SUBTREE_SPP_LIST = [
    "Amborella trichopoda",
    "Carex littledai",
    "Panicum virgatum",
    "Sorghum bicolor",
    "Zea mays",
    "Oryza sativa",
    "Brachypodium distachyon",
    "Hordeum vulgare",
    "Thinopyrum intermedium",
    "Aquilegia coerulea",
    "Amaranthus hypochondriacus",
    "Silene latifolia",
    "Arabidopsis thaliana",
    "Ligum trigynum",
    "Malus domestica",
    "Prunus persica",
    "Glycine max",
    "Medicago truncatula",
    "Trifolium repens",
    "Trofolium pratense",
    "Vaccinium darrowi",
    "Rhododendron vialli",
    "Cornus florida",
    "Hydrangea quercifolia",
    "Daucus carota",
    "Hydocotyle leucocephala",
    "Helianthus annuus",
    "Lactuca sativa",
    "Cuscuta campestris",
    "Solanum lycopersicum",
    "Catharanthus roseus",
    "Coffea arabica",
    "Abeliophyllum distichum",
    "Handroanthus impetiginosus",
    "Sesamum indicum",
    "Salvia mitiorrhiza",
    "Mimulus guttatus",
    "Rehmannia glutinosa",
    "Lindenbergia phillipensis",
    "Lindenbergia luchunensis",
    "Phelipanche aegyptiaca",
    "Orobanche cernua",
    "Orobanche cumana",
    "Orobanche gracilis",
    "Orobanche hederae",
    "Orobanche minor",
    "Striga hermonthica",
    "Striga asiatica",
    "Castilleja foliolosa",
    "Phtheirospermum japonicum",
    "Pedicularis groenlandica",
    "Pedicularis cranolopha",
]

In [23]:
SUBTREE_SPP_LIST = [
    "Castilleja caudata",
    "Castilleja campestris",
    "Orobanche cumana",
    "Pedicularis anas",
    "Pedicularis groenlandica",
    "Pedicularis canadensis",
    "Pedicularis latituba",
    "Mimulus guttatus",
    "Aquilegia coerulea",
    "Delphinium exaltatum",
    "Amaranthus greggii",
    "Amaranthus tuberculatus",
    "Amaranthus tricolor",
    "Beta vulgaris",
    "Quercus minima",
    "Quercus macrocarpa",
    "Quercus mexicana",
    "Quercus virginiana",
    "Quercus alba",
    "Quercus rubra",
    "Quercus californica",
    "Boswellia sacra",
]

SUBTREE_GEN_LIST = [
    "Castilleja",
    "Orobanche",
    "Phelipanche",
    "Lindenbergia",
    "Rehmannia",
    "Pedicularis",
    "Mimulus",
    "Erythranthe",
    "Aquilegia",
    "Quercus",
    "Fagus",
    "Boswellia",
    "Delphinium",
]

### Get resolved names

In [25]:
names = toytree.otol.resolve_taxonomic_names(
    SUBTREE_SPP_LIST,
    approximate=True,
    context="Angiosperms",
    include_synonyms=True,
    on_ambiguous='first', 
    on_unresolved="warn",
)
names

,query,status,matched_name,rank,taxon_name,ott_id,ncbi_id,is_synonym,reason
0,Castilleja caudata,matched,Castilleja caudata,species,Castilleja caudata,338833,395288,False,ok
1,Castilleja campestris,matched,Castilleja campestris,species,Castilleja campestris,83184,428863,False,ok
2,Orobanche cumana,matched,Orobanche cumana,varietas,Orobanche cernua var. cumana,1010133,78542,True,ok
3,Pedicularis anas,matched,Pedicularis anas,species,Pedicularis anas,1032908,216507,False,ok
4,Pedicularis groenlandica,matched,Pedicularis groenlandica,species,Pedicularis groenlandica,261492,262426,False,ok
5,Pedicularis canadensis,matched,Pedicularis canadensis,species,Pedicularis canadensis,3882309,1325716,False,ok
6,Pedicularis latituba,matched,Pedicularis latituba,species,Pedicularis latituba,869589,1043536,False,ok
7,Mimulus guttatus,matched,Mimulus guttatus,species,Erythranthe guttata,504496,4155,True,resolved_first_of_2
8,Aquilegia coerulea,matched,Aquilegia coerulea,species,Aquilegia coerulea,192307,218851,False,ok
9,Delphinium exaltatum,matched,Delphinium exaltatum,species,Delphinium exaltatum,693550,46987,False,ok
10,Amaranthus greggii,matched,Amaranthus greggii,species,Amaranthus greggii,151502,240022,False,ok
11,Amaranthus tuberculatus,matched,Amaranthus tuberculatus,species,Amaranthus tuberculatus,828461,277990,False,ok
12,Amaranthus tricolor,matched,Amaranthus tricolor,species,Amaranthus tricolor,653438,29722,False,ok
13,Beta vulgaris,matched,Beta vulgaris,species,Beta vulgaris,273185,161934,False,ok
14,Quercus minima,matched,Quercus minima,species,Quercus minima,117134,262625,False,ok
15,Quercus macrocarpa,matched,Quercus macrocarpa,species,Quercus macrocarpa,37377,519047,False,resolved_first_of_2
16,Quercus mexicana,matched,Quercus mexicana,species,Quercus mexicana,3930585,1266341,False,resolved_first_of_2
17,Quercus virginiana,matched,Quercus virginiana,species,Quercus virginiana,272703,58333,False,ok
18,Quercus alba,matched,Quercus alba,species,Quercus alba,791112,3513,False,ok
19,Quercus rubra,matched,Quercus rubra,species,Quercus rubra,791115,3512,False,ok
20,Quercus californica,matched,Quercus californica,species,Quercus kelloggii,403375,97698,True,ok
21,Boswellia sacra,matched,Boswellia sacra,species,Boswellia sacra,815270,173701,False,ok

In [26]:
# toytree.otol.fetch_json_taxon_info(1041561)

In [27]:
# toytree.otol.fetch_json_match_names("Striga asiatica")[0]['matches'][0]['taxon']

### Get induced tree

In [28]:
ttree = toytree.otol.fetch_newick_subtree_from_taxonomy(names)

In [30]:
ttree.draw('s', node_hover=True);

In [31]:
itree = toytree.otol.fetch_newick_induced_tree_otol(names, constrain_by_taxonomy=True)

In [33]:
itree.draw('s', node_hover=True);

In [21]:
times = toytree.otol.get_timetree_node_ages(itree, max_pairs=3)

TimeTree node-age retrieval completed with non-ok nodes: 7 total (7 unresolved, 0 errors).

In [22]:
itree.set_node_data("height", dict(times.age)).ladderize().draw(scale_bar=True);

## Fetching a study by Author or DOI

In [ ]:
toytree.otol.fetch_json_studies_by_author(["Zuntini, A.R."])

In [4]:
toytree.otol.fetch_json_studies_by_doi('https://doi.org/10.1038/s41586-024-07324-0')

[{'ot:studyId': 'ot_2304',
  'ot:studyPublicationReference': 'Zuntini, A.R., Carruthers, T., Maurin, O. et al. Phylogenomics and the rise of the angiosperms. Nature (2024). https://doi.org/10.1038/s41586-024-07324-0',
  'ot:curatorName': ['Emily Jane McTavish', 'Brian O&#x27;Meara'],
  'ot:studyYear': 2024,
  'ot:focalClade': 5268475,
  'ot:focalCladeOTTTaxonName': 'Archaeplastida',
  'ot:dataDeposit': 'https://www.gbif.org/dataset/4195e042-b632-47ba-9545-32a5e3033ff7',
  'ot:studyPublication': 'https://doi.org/10.1038/s41586-024-07324-0',
  'ot:tag': []}]

In [13]:
# toytree.otol.fetch_json_induced_subtree(SUBTREE_SPP_LIST)

In [4]:
resolved = toytree.otol.resolve_taxonomic_names(
    SUBTREE_SPP_LIST,
    on_ambiguous="first",
    on_unresolved="raise",
)
nwk1 = toytree.otol.fetch_newick_induced_tree_otol(
    resolved, constrain_by_taxonomy=False
)

In [5]:
toytree.tree(nwk1).draw('s');
toytree.tree(nwk1).mod.remove_unary_nodes().draw('s', node_hover=True);

In [31]:
nwk2 = toytree.otol.fetch_newick_subtree_from_taxonomy(resolved)

In [32]:
toytree.tree(nwk2).mod.remove_unary_nodes().draw('s', node_hover=True);

In [29]:
nwk3 = toytree.otol.fetch_newick_induced_tree_otol(
    resolved, constrain_by_taxonomy=True
)

In [30]:
t = toytree.tree(nwk3)
t.mod.remove_unary_nodes().draw('s', node_hover=True);

In [24]:
t2 = toytree.ToyTree(t.treenode.children[0]._detach())

In [25]:
t2.draw('s');

### Fetching a tree from a published study

In [22]:
res = toytree.otol.fetch_json_induced_subtree(SUBTREE_GEN_LIST)
b = res['broken']
n = res['newick']
t = toytree.tree(n)

In [23]:
res

{'broken': {'ott1028998': 'mrcaott288140ott863220',
  'ott317400': 'ott5263556',
  'ott733734': 'mrcaott96ott39620',
  'ott791121': 'mrcaott37377ott106844',
  'ott918756': 'ott5263556',
  'ott989660': 'mrcaott1452ott33561'},
 'newick': "(((((((((((((((((((((((((mrcaott96ott39620)Burseraceae_ott350867)mrcaott96ott21231)mrcaott96ott982264)mrcaott96ott655994)mrcaott96ott1860)mrcaott96ott9337)mrcaott96ott24291)mrcaott96ott84975)mrcaott96ott378)mrcaott2ott96)mrcaott2ott29446)mrcaott2ott345)mrcaott2ott50744,(((((mrcaott37377ott106844,mrcaott288140ott863220)mrcaott37377ott288140)mrcaott32687ott37377)Fagales_ott267709)mrcaott579ott32687)mrcaott371ott579)mrcaott2ott371)mrcaott2ott1276)mrcaott2ott607)mrcaott2ott2464)mrcaott2ott8384)mrcaott2ott20991)mrcaott2ott557,(((((((((((((((((((((((((((Erythranthe_ott5334418)mrcaott75211ott422994)mrcaott39175ott75211,((Mimulus_ott596470)mrcaott423002ott548451)mrcaott423002ott1024159)mrcaott39175ott423002)mrcaott39175ott108490)mrcaott1452ott39175)mrcaott1452ott432231)mrcaott1452ott33561)mrcaott1016ott1452)mrcaott1016ott5046)mrcaott1016ott10430)mrcaott1016ott295840)mrcaott1016ott55260)mrcaott1016ott22352)mrcaott1016ott108502)mrcaott248ott1016)'Core_Lamiales ott5263556')mrcaott248ott55259)mrcaott248ott11341)Lamiales_ott23736)mrcaott248ott1191)mrcaott248ott101831)mrcaott248ott68444)mrcaott248ott5942)mrcaott248ott320)mrcaott248ott650)mrcaott248ott308117)mrcaott248ott67236)mrcaott2ott248)mrcaott2ott10053)mrcaott2ott8379)mrcaott2ott969,(((((((((((((Aquilegia_ott964055)mrcaott38573ott7049099)mrcaott38573ott949642)mrcaott34125ott38573)Thalictroideae_ott5479017)mrcaott2441ott22673)mrcaott2441ott203150)mrcaott2441ott1072050)Ranunculaceae_ott387826)mrcaott2441ott21786)mrcaott2441ott3773)mrcaott2441ott92057)mrcaott2441ott3851)Ranunculales_ott872975)mrcaott2ott2441;",
 'supporting_studies': ['ot_311@tree1',
  'ot_1624@Tr85668',
  'ot_2291@tree7',
  'ot_2304@tree2',
  'ot_1489@tree1',
  'ot_502@tree1',
  'ot_535@tree1',
  'pg_2712@tree6296',
  'pg_2820@tree6566',
  'pg_2539@tree6294',
  'ot_2304@tree4',
  'pg_1944@tree3959',
  'ot_1176@tree1',
  'ot_1417@Tr94055',
  'ot_2116@tree1',
  'ot_859@tree1',
  'ot_1489@tree2',
  'pg_2644@tree6164',
  'ot_1960@tree2',
  'pg_713@tree1287',
  'pg_225@tree5991',
  'ot_1489@tree4']}

In [39]:
# store the rooting info in taxatree
toytree.tree(nwk).draw('s', tip_labels_align=True, node_hover=True);

In [16]:
toytree.otol.fetch_json_mrca(["Quercus", "Boswellia"])

{'mrca': {'conflicts_with': {'ot_1360@Tr93591': ['Tn13791757',
    'Tn13791760',
    'Tn13791786',
    'Tn13791793',
    'Tn13791825',
    'Tn13791850'],
   'ot_1417@Tr94055': ['Tn13857155', 'Tn13857203', 'Tn13857325', 'Tn13857439'],
   'ot_1489@tree1': ['node112', 'node113', 'node122', 'node85'],
   'ot_1489@tree2': ['node282',
    'node298',
    'node299',
    'node301',
    'node305',
    'node307'],
   'ot_1489@tree4': ['node407', 'node408'],
   'ot_1624@Tr85668': ['Tn12610217'],
   'ot_2089@Tr65393': ['Tn10412906',
    'Tn10412909',
    'Tn10412938',
    'Tn10412976',
    'Tn10412996',
    'Tn10413034',
    'Tn10413106',
    'Tn10413111',
    'Tn10413114',
    'Tn10413123',
    'Tn10413131',
    'Tn10413152',
    'Tn10413259',
    'Tn10413272',
    'Tn10413319',
    'Tn10413322',
    'Tn10413330',
    'Tn10413361',
    'Tn10413476',
    'Tn10413514',
    'Tn10413560',
    'Tn10413564',
    'Tn10413587',
    'Tn10413637',
    'Tn10413676',
    'Tn10413688',
    'Tn10413716'],
   'ot_2116@tree1': ['node155'],
   'ot_2291@tree7': ['node145446',
    'node148192',
    'node148193',
    'node148197',
    'node148469',
    'node148523',
    'node148524',
    'node148525',
    'node148527',
    'node148529',
    'node148530',
    'node148533',
    'node148534',
    'node148566',
    'node148567',
    'node148573',
    'node148574',
    'node148576',
    'node148578',
    'node148801',
    'node148802',
    'node158125',
    'node158267',
    'node166951',
    'node184719',
    'node184720',
    'node184738',
    'node185136',
    'node185146',
    'node185172',
    'node185188',
    'node185216',
    'node185218',
    'node185246',
    'node185256',
    'node185257',
    'node185258',
    'node185259',
    'node185261',
    'node185262',
    'node185264',
    'node185266',
    'node185280',
    'node185281',
    'node185282',
    'node185308',
    'node185469',
    'node185471',
    'node185479',
    'node185509',
    'node185531',
    'node185533',
    'node185545',
    'node185549',
    'node185561',
    'node185563',
    'node185565',
    'node185592',
    'node185608',
    'node185609',
    'node185613',
    'node185615',
    'node185617',
    'node185621',
    'node185622',
    'node185623',
    'node185625',
    'node185626',
    'node185647',
    'node185649',
    'node185651',
    'node185653',
    'node185654',
    'node185664',
    'node185665',
    'node185666',
    'node185668',
    'node185670',
    'node185672',
    'node185696',
    'node185697',
    'node185703',
    'node185705',
    'node185712',
    'node185746',
    'node185747',
    'node185748',
    'node185762',
    'node185763',
    'node185767',
    'node185769',
    'node185771',
    'node185779',
    'node185833',
    'node190093',
    'node190094',
    'node190095',
    'node190853',
    'node190854',
    'node191172',
    'node191173',
    'node191387',
    'node191388'],
   'ot_311@tree1': ['node21593',
    'node21723',
    'node21724',
    'node21738',
    'node21740',
    'node21742',
    'node21744',
    'node21745',
    'node21746',
    'node21748',
    'node21985',
    'node22025',
    'node22033',
    'node28470'],
   'ot_502@tree1': ['node108', 'node539', 'node549', 'node550'],
   'ot_535@tree1': ['node35', 'node62', 'node63', 'node72'],
   'ot_859@tree1': ['node74', 'node75'],
   'pg_2539@tree6294': ['node1095082', 'node1095106', 'node1095165'],
   'pg_2712@tree6296': ['node1095851',
    'node1095852',
    'node1095853',
    'node1095854',
    'node1095879',
    'node1095934'],
   'pg_2820@tree6566': ['node1140396',
    'node1140397',
    'node1140442',
    'node1140443',
    'node1140465']},
  'node_id': 'mrcaott2ott371',
  'num_tips': 88231,
  'partial_path_of': {'ot_1176@tree1': 'node9', 'ot_1960@tree2': 'node93'},
  'supported_by': {'ot_2304@tree2': 'node13855', 'ot_2304@tree4': 'node21026'},
  'terminal': {'ot_2037@tree13': 'node741',
   'ot_766@Tr85440': 'Tn12578681',
   'pg_1242@tree2507': 'ott339346',
   'pg_2822@tree6569': 'node1141898'}},
 'nearest_taxon': {'name': 'Mesangiospermae',
  'ott_id': 5298374,
  'rank': 'no rank',
  'tax_sources': ['ncbi:1437183'],
  'unique_name': 'Mesangiospermae'},
 'source_id_map': {'ot_1176@tree1': {'git_sha': '',
   'study_id': 'ot_1176',
   'tree_id': 'tree1'},
  'ot_1360@Tr93591': {'git_sha': '',
   'study_id': 'ot_1360',
   'tree_id': 'Tr93591'},
  'ot_1417@Tr94055': {'git_sha': '',
   'study_id': 'ot_1417',
   'tree_id': 'Tr94055'},
  'ot_1489@tree1': {'git_sha': '', 'study_id': 'ot_1489', 'tree_id': 'tree1'},
  'ot_1489@tree2': {'git_sha': '', 'study_id': 'ot_1489', 'tree_id': 'tree2'},
  'ot_1489@tree4': {'git_sha': '', 'study_id': 'ot_1489', 'tree_id': 'tree4'},
  'ot_1624@Tr85668': {'git_sha': '',
   'study_id': 'ot_1624',
   'tree_id': 'Tr85668'},
  'ot_1960@tree2': {'git_sha': '', 'study_id': 'ot_1960', 'tree_id': 'tree2'},
  'ot_2037@tree13': {'git_sha': '',
   'study_id': 'ot_2037',
   'tree_id': 'tree13'},
  'ot_2089@Tr65393': {'git_sha': '',
   'study_id': 'ot_2089',
   'tree_id': 'Tr65393'},
  'ot_2116@tree1': {'git_sha': '', 'study_id': 'ot_2116', 'tree_id': 'tree1'},
  'ot_2291@tree7': {'git_sha': '', 'study_id': 'ot_2291', 'tree_id': 'tree7'},
  'ot_2304@tree2': {'git_sha': '', 'study_id': 'ot_2304', 'tree_id': 'tree2'},
  'ot_2304@tree4': {'git_sha': '', 'study_id': 'ot_2304', 'tree_id': 'tree4'},
  'ot_311@tree1': {'git_sha': '', 'study_id': 'ot_311', 'tree_id': 'tree1'},
  'ot_502@tree1': {'git_sha': '', 'study_id': 'ot_502', 'tree_id': 'tree1'},
  'ot_535@tree1': {'git_sha': '', 'study_id': 'ot_535', 'tree_id': 'tree1'},
  'ot_766@Tr85440': {'git_sha': '',
   'study_id': 'ot_766',
   'tree_id': 'Tr85440'},
  'ot_859@tree1': {'git_sha': '', 'study_id': 'ot_859', 'tree_id': 'tree1'},
  'pg_1242@tree2507': {'git_sha': '',
   'study_id': 'pg_1242',
   'tree_id': 'tree2507'},
  'pg_2539@tree6294': {'git_sha': '',
   'study_id': 'pg_2539',
   'tree_id': 'tree6294'},
  'pg_2712@tree6296': {'git_sha': '',
   'study_id': 'pg_2712',
   'tree_id': 'tree6296'},
  'pg_2820@tree6566': {'git_sha': '',
   'study_id': 'pg_2820',
   'tree_id': 'tree6566'},
  'pg_2822@tree6569': {'git_sha': '',
   'study_id': 'pg_2822',
   'tree_id': 'tree6569'}},
 'synth_id': 'opentree16.1'}

In [117]:
if b:

    # get lineages for all passed tips
    lineages = toytree.otol.fetch_json_taxon_info(SUBTREE_GEN_LIST, include_lineage=True)

    # iterate over broken nodes to insert
    # TODO: sort so mrca targets go first
    for key, val in b.items():
        
        if val.startswith("o"):
            continue
    
        # build name of broken node
        name = toytree.otol.fetch_json_taxon_info(key)[0].get("name", key)
        name = f"{name}_{key}"

        # find lowest shared rank with existing taxa
        
        
        # try to insert at genus if mrca with any existing
        for node in t:
    
        # try to insert at family
    
        # ...
        
        t.mod.add_child_node(f"~{val}", name=name, dist=1, inplace=True)

NameError: name 'lineages' is not defined

In [89]:
name = toytree.otol.fetch_json_taxon_info("ott918756")[0].get("name")
name

'Orobanche'

In [118]:
t.draw();

In [104]:
t.get_nodes("~Orob")

[{'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Pedicularideae',
  'ott_id': 5144557,
  'rank': 'tribe',
  'source': 'ott3.7draft3',
  'synonyms': [],
  'tax_sources': ['ncbi:1325730'],
  'unique_name': 'Pedicularideae'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Orobanchaceae',
  'ott_id': 23373,
  'rank': 'family',
  'source': 'ott3.7draft3',
  'synonyms': ['Aeginetiaceae',
   'Cyclocheilaceae',
   'Cyclocheileae',
   'Melampyraceae',
   'Nesogenaceae',
   'Pedicularidaceae',
   'Phelypaeaceae',
   'Rehmanniaceae',
   'Rhinanthaceae'],
  'tax_sources': ['study713:78',
   'ncbi:91896',
   'worms:382476',
   'gbif:6651',
   'irmng:119096'],
  'unique_name': 'Orobanchaceae'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'higher_core_Lamiales',
  'ott_id': 5264061,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': [],
  'tax_sources': ['study713:49'],
  'unique_name': 'higher_core_Lamiales'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Core_Lamiales',
  'ott_id': 5263556,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': [],
  'tax_sources': ['study713:13'],
  'unique_name': 'Core_Lamiales'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Lamiales',
  'ott_id': 23736,
  'rank': 'order',
  'source': 'ott3.7draft3',
  'synonyms': ['Scrophulariales'],
  'tax_sources': ['study713:1',
   'ncbi:4143',
   'worms:234498',
   'gbif:408',
   'irmng:12140',
   'irmng:11489'],
  'unique_name': 'Lamiales'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'lamiids',
  'ott_id': 596112,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': ['Gentiananae', 'euasterids I'],
  'tax_sources': ['ncbi:91888'],
  'unique_name': 'lamiids'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'asterids',
  'ott_id': 1008294,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': ['Asteridae'],
  'tax_sources': ['ncbi:71274'],
  'unique_name': 'asterids'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Pentapetalae',
  'ott_id': 5316182,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': [],
  'tax_sources': ['ncbi:1437201'],
  'unique_name': 'Pentapetalae'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Gunneridae',
  'ott_id': 853757,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': ['core eudicots', 'core eudicotyledons'],
  'tax_sources': ['ncbi:91827'],
  'unique_name': 'Gunneridae'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'eudicotyledons',
  'ott_id': 431495,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': [],
  'tax_sources': ['ncbi:71240'],
  'unique_name': 'eudicotyledons'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Mesangiospermae',
  'ott_id': 5298374,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': [],
  'tax_sources': ['ncbi:1437183'],
  'unique_name': 'Mesangiospermae'},
 {'flags': ['sibling_higher'],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Magnoliopsida',
  'ott_id': 99252,
  'rank': 'class',
  'source': 'ott3.7draft3',
  'synonyms': ['Angiospermae', 'Magnoliophyta'],
  'tax_sources': ['ncbi:3398', 'worms:182757', 'gbif:220', 'irmng:1102'],
  'unique_name': 'Magnoliopsida'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Spermatophyta',
  'ott_id': 10218,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': [],
  'tax_sources': ['ncbi:58024'],
  'unique_name': 'Spermatophyta'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Euphyllophyta',
  'ott_id': 1007992,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': ['euphyllophytes'],
  'tax_sources': ['ncbi:78536'],
  'unique_name': 'Euphyllophyta'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Tracheophyta',
  'ott_id': 10210,
  'rank': 'phylum',
  'source': 'ott3.7draft3',
  'synonyms': ['Arthrophyta',
   'Coniferophyta',
   'Cycadophyta',
   'Equisetophyta',
   'Ginkgophyta',
   'Gnetophyta',
   'Lycopodiophyta',
   'Magnoliophyta',
   'Microphyllophyta',
   'Polypodiophyta',
   'Psilophyta',
   'Psilotophyta',
   'Pteridophyta',
   'Pterophyta'],
  'tax_sources': ['ncbi:58023', 'worms:596326', 'gbif:7707728', 'irmng:227'],
  'unique_name': 'Tracheophyta'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Embryophyta',
  'ott_id': 56610,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': [],
  'tax_sources': ['ncbi:3193'],
  'unique_name': 'Embryophyta'},
 {'flags': ['sibling_higher'],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Streptophyta',
  'ott_id': 916750,
  'rank': 'phylum',
  'source': 'ott3.7draft3',
  'synonyms': ['Charophyta/Embryophyta group',
   'Streptophytina',
   'charophyte/embryophyte group'],
  'tax_sources': ['ncbi:35493', 'worms:536191'],
  'unique_name': 'Streptophyta'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Chloroplastida',
  'ott_id': 361838,
  'rank': 'kingdom',
  'source': 'ott3.7draft3',
  'synonyms': ['Chlorobionta',
   'Chlorophyta/Embryophyta group',
   'Viridiplantae',
   'chlorophyte/embryophyte group'],
  'tax_sources': ['silva:D13324/#3', 'study713:361838', 'ncbi:33090'],
  'unique_name': 'Chloroplastida'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Archaeplastida',
  'ott_id': 5268475,
  'rank': 'kingdom',
  'source': 'ott3.7draft3',
  'synonyms': ['Plantae'],
  'tax_sources': ['silva:D13324/#2', 'worms:3', 'gbif:6', 'irmng:15'],
  'unique_name': 'Archaeplastida'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'Eukaryota',
  'ott_id': 304358,
  'rank': 'domain',
  'source': 'ott3.7draft3',
  'synonyms': ['D4P07G08',
   'DH147-EKD10',
   'DH147-EKD23',
   'Eucaryotae',
   'Eukarya',
   'Eukaryotae',
   'LG25-05',
   'NAMAKO-1',
   'RT5iin25',
   'SA1-3C06'],
  'tax_sources': ['silva:D11377/#1', 'ncbi:2759'],
  'unique_name': 'Eukaryota'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'cellular organisms',
  'ott_id': 93302,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': ['biota'],
  'tax_sources': ['ncbi:131567'],
  'unique_name': 'cellular organisms'},
 {'flags': [],
  'is_suppressed': False,
  'is_suppressed_from_synth': False,
  'name': 'life',
  'ott_id': 805080,
  'rank': 'no rank',
  'source': 'ott3.7draft3',
  'synonyms': ['all'],
  'tax_sources': ['silva:0', 'ncbi:1', 'gbif:0', 'irmng:0'],
  'unique_name': 'life'}]

In [126]:
toytree.otol.fetch_json_mrca(["Orobanche", "Lindenbergia"])

{'mrca': {'conflicts_with': {'ot_2304@tree2': ['node8859',
    'node8941',
    'node9051',
    'node9075',
    'node9393',
    'node9403',
    'node9404',
    'node9405']},
  'node_id': 'ott5263556',
  'num_tips': 28827,
  'partial_path_of': {'ot_1417@Tr94055': 'Tn13857041',
   'ot_1624@Tr85668': 'Tn12609901',
   'ot_535@tree1': 'node112',
   'ot_859@tree1': 'node177',
   'pg_2820@tree6566': 'node1140546'},
  'supported_by': {'ot_2304@tree4': 'node20399',
   'ot_311@tree1': 'node60025',
   'ot_502@tree1': 'node986',
   'ott3.7draft3': 'ott5263556',
   'pg_2539@tree6294': 'node1094751',
   'pg_713@tree1287': 'node435792'},
  'taxon': {'name': 'Core_Lamiales',
   'ott_id': 5263556,
   'rank': 'no rank',
   'tax_sources': ['study713:13'],
   'unique_name': 'Core_Lamiales'},
  'terminal': {'ot_2089@Tr65393': 'Tn10413075', 'ot_2116@tree1': 'node173'}},
 'source_id_map': {'ot_1417@Tr94055': {'git_sha': '',
   'study_id': 'ot_1417',
   'tree_id': 'Tr94055'},
  'ot_1624@Tr85668': {'git_sha': '',
   'study_id': 'ot_1624',
   'tree_id': 'Tr85668'},
  'ot_2089@Tr65393': {'git_sha': '',
   'study_id': 'ot_2089',
   'tree_id': 'Tr65393'},
  'ot_2116@tree1': {'git_sha': '', 'study_id': 'ot_2116', 'tree_id': 'tree1'},
  'ot_2304@tree2': {'git_sha': '', 'study_id': 'ot_2304', 'tree_id': 'tree2'},
  'ot_2304@tree4': {'git_sha': '', 'study_id': 'ot_2304', 'tree_id': 'tree4'},
  'ot_311@tree1': {'git_sha': '', 'study_id': 'ot_311', 'tree_id': 'tree1'},
  'ot_502@tree1': {'git_sha': '', 'study_id': 'ot_502', 'tree_id': 'tree1'},
  'ot_535@tree1': {'git_sha': '', 'study_id': 'ot_535', 'tree_id': 'tree1'},
  'ot_859@tree1': {'git_sha': '', 'study_id': 'ot_859', 'tree_id': 'tree1'},
  'ott3.7draft3': {'taxonomy': 'ott3.7draft3'},
  'pg_2539@tree6294': {'git_sha': '',
   'study_id': 'pg_2539',
   'tree_id': 'tree6294'},
  'pg_2820@tree6566': {'git_sha': '',
   'study_id': 'pg_2820',
   'tree_id': 'tree6566'},
  'pg_713@tree1287': {'git_sha': '',
   'study_id': 'pg_713',
   'tree_id': 'tree1287'}},
 'synth_id': 'opentree16.1'}

In [79]:
toytree.otol.fetch_json_node_info("ott918756")

[{'broken': True,
  'conflicts_with': {'ot_2304@tree2': ['node8859',
    'node8941',
    'node9051',
    'node9075',
    'node9393',
    'node9403',
    'node9404',
    'node9405']},
  'node_id': 'ott5263556',
  'num_tips': 28827,
  'partial_path_of': {'ot_1417@Tr94055': 'Tn13857041',
   'ot_1624@Tr85668': 'Tn12609901',
   'ot_535@tree1': 'node112',
   'ot_859@tree1': 'node177',
   'pg_2820@tree6566': 'node1140546'},
  'query': 'ott918756',
  'source_id_map': {'ot_1417@Tr94055': {'git_sha': '',
    'study_id': 'ot_1417',
    'tree_id': 'Tr94055'},
   'ot_1624@Tr85668': {'git_sha': '',
    'study_id': 'ot_1624',
    'tree_id': 'Tr85668'},
   'ot_2089@Tr65393': {'git_sha': '',
    'study_id': 'ot_2089',
    'tree_id': 'Tr65393'},
   'ot_2116@tree1': {'git_sha': '', 'study_id': 'ot_2116', 'tree_id': 'tree1'},
   'ot_2304@tree2': {'git_sha': '', 'study_id': 'ot_2304', 'tree_id': 'tree2'},
   'ot_2304@tree4': {'git_sha': '', 'study_id': 'ot_2304', 'tree_id': 'tree4'},
   'ot_311@tree1': {'git_sha': '', 'study_id': 'ot_311', 'tree_id': 'tree1'},
   'ot_502@tree1': {'git_sha': '', 'study_id': 'ot_502', 'tree_id': 'tree1'},
   'ot_535@tree1': {'git_sha': '', 'study_id': 'ot_535', 'tree_id': 'tree1'},
   'ot_859@tree1': {'git_sha': '', 'study_id': 'ot_859', 'tree_id': 'tree1'},
   'ott3.7draft3': {'taxonomy': 'ott3.7draft3'},
   'pg_2539@tree6294': {'git_sha': '',
    'study_id': 'pg_2539',
    'tree_id': 'tree6294'},
   'pg_2820@tree6566': {'git_sha': '',
    'study_id': 'pg_2820',
    'tree_id': 'tree6566'},
   'pg_713@tree1287': {'git_sha': '',
    'study_id': 'pg_713',
    'tree_id': 'tree1287'}},
  'supported_by': {'ot_2304@tree4': 'node20399',
   'ot_311@tree1': 'node60025',
   'ot_502@tree1': 'node986',
   'ott3.7draft3': 'ott5263556',
   'pg_2539@tree6294': 'node1094751',
   'pg_713@tree1287': 'node435792'},
  'synth_id': 'opentree16.1',
  'taxon': {'name': 'Core_Lamiales',
   'ott_id': 5263556,
   'rank': 'no rank',
   'tax_sources': ['study713:13'],
   'unique_name': 'Core_Lamiales'},
  'terminal': {'ot_2089@Tr65393': 'Tn10413075', 'ot_2116@tree1': 'node173'}}]

In [65]:
toytree.otol.match_names(SUBTREE_GEN_LIST, output="raw")

{'context': 'Flowering plants',
 'governing_code': 'ICN',
 'includes_approximate_matches': False,
 'includes_deprecated_taxa': False,
 'includes_suppressed_names': False,
 'matched_names': ['Castilleja',
  'Orobanche',
  'Pedicularis',
  'Mimulus',
  'Erythranthe',
  'Aquilegia',
  'Quercus',
  'Boswellia'],
 'results': [{'matches': [{'is_approximate_match': False,
     'is_synonym': False,
     'matched_name': 'Castilleja',
     'nomenclature_code': 'ICN',
     'score': 1.0,
     'search_string': 'castilleja',
     'taxon': {'flags': [],
      'is_suppressed': False,
      'is_suppressed_from_synth': False,
      'name': 'Castilleja',
      'ott_id': 317400,
      'rank': 'genus',
      'source': 'ott3.7draft3',
      'synonyms': ['Euchroma', 'Gentrya', 'Ophiocephalus'],
      'tax_sources': ['study713:88',
       'ncbi:46036',
       'gbif:3170565',
       'irmng:1010255'],
      'unique_name': 'Castilleja'}}],
   'name': 'Castilleja'},
  {'matches': [{'is_approximate_match': False,
     'is_synonym': False,
     'matched_name': 'Orobanche',
     'nomenclature_code': 'ICN',
     'score': 1.0,
     'search_string': 'orobanche',
     'taxon': {'flags': [],
      'is_suppressed': False,
      'is_suppressed_from_synth': False,
      'name': 'Orobanche',
      'ott_id': 918756,
      'rank': 'genus',
      'source': 'ott3.7draft3',
      'synonyms': ['Aphyllon', 'Boulardia', 'Myzorrhiza', 'Phelipanche'],
      'tax_sources': ['study713:81',
       'ncbi:36747',
       'worms:425727',
       'gbif:3173259',
       'irmng:1019858'],
      'unique_name': 'Orobanche'}}],
   'name': 'Orobanche'},
  {'matches': [{'is_approximate_match': False,
     'is_synonym': False,
     'matched_name': 'Pedicularis',
     'nomenclature_code': 'ICN',
     'score': 1.0,
     'search_string': 'pedicularis',
     'taxon': {'flags': ['sibling_higher'],
      'is_suppressed': False,
      'is_suppressed_from_synth': False,
      'name': 'Pedicularis',
      'ott_id': 989660,
      'rank': 'genus',
      'source': 'ott3.7draft3',
      'synonyms': ['Pediculariopsis'],
      'tax_sources': ['study713:86',
       'ncbi:43174',
       'gbif:3171670',
       'irmng:1038450'],
      'unique_name': 'Pedicularis'}}],
   'name': 'Pedicularis'},
  {'matches': [{'is_approximate_match': False,
     'is_synonym': False,
     'matched_name': 'Mimulus',
     'nomenclature_code': 'ICN',
     'score': 1.0,
     'search_string': 'mimulus',
     'taxon': {'flags': [],
      'is_suppressed': False,
      'is_suppressed_from_synth': False,
      'name': 'Mimulus',
      'ott_id': 596470,
      'rank': 'genus',
      'source': 'ott3.7draft3',
      'synonyms': ['Diplacus', 'Eunanus', 'Mimetanthe'],
      'tax_sources': ['study713:74',
       'ncbi:4154',
       'gbif:6008574',
       'irmng:1301444',
       'irmng:1301412'],
      'unique_name': 'Mimulus'}}],
   'name': 'Mimulus'},
  {'matches': [{'is_approximate_match': False,
     'is_synonym': False,
     'matched_name': 'Erythranthe',
     'nomenclature_code': 'ICN',
     'score': 1.0,
     'search_string': 'erythranthe',
     'taxon': {'flags': [],
      'is_suppressed': False,
      'is_suppressed_from_synth': False,
      'name': 'Erythranthe',
      'ott_id': 5334418,
      'rank': 'genus',
      'source': 'ott3.7draft3',
      'synonyms': [],
      'tax_sources': ['ncbi:1502711', 'gbif:3171742', 'irmng:1042751'],
      'unique_name': 'Erythranthe'}}],
   'name': 'Erythranthe'},
  {'matches': [{'is_approximate_match': False,
     'is_synonym': False,
     'matched_name': 'Aquilegia',
     'nomenclature_code': 'ICN',
     'score': 1.0,
     'search_string': 'aquilegia',
     'taxon': {'flags': [],
      'is_suppressed': False,
      'is_suppressed_from_synth': False,
      'name': 'Aquilegia',
      'ott_id': 964055,
      'rank': 'genus',
      'source': 'ott3.7draft3',
      'synonyms': [],
      'tax_sources': ['ncbi:3450', 'gbif:3033167', 'irmng:1025084'],
      'unique_name': 'Aquilegia'}}],
   'name': 'Aquilegia'},
  {'matches': [{'is_approximate_match': False,
     'is_synonym': False,
     'matched_name': 'Quercus',
     'nomenclature_code': 'ICN',
     'score': 1.0,
     'search_string': 'quercus',
     'taxon': {'flags': [],
      'is_suppressed': False,
      'is_suppressed_from_synth': False,
      'name': 'Quercus',
      'ott_id': 791121,
      'rank': 'genus',
      'source': 'ott3.7draft3',
      'synonyms': ['Cyclobalanopsis', 'Dryopsila', 'Ilex', 'Perytis'],
      'tax_sources': ['ncbi:3511',
       'gbif:2877951',
       'irmng:1353947',
       'irmng:1088291',
       'irmng:1022836'],
      'unique_name': 'Quercus'}}],
   'name': 'Quercus'},
  {'matches': [{'is_approximate_match': False,
     'is_synonym': False,
     'matched_name': 'Boswellia',
     'nomenclature_code': 'ICN',
     'score': 1.0,
     'search_string': 'boswellia',
     'taxon': {'flags': [],
      'is_suppressed': False,
      'is_suppressed_from_synth': False,
      'name': 'Boswellia',
      'ott_id': 733734,
      'rank': 'genus',
      'source': 'ott3.7draft3',
      'synonyms': [],
      'tax_sources': ['ncbi:80276', 'gbif:3190439', 'irmng:1307840'],
      'unique_name': 'Boswellia'}}],
   'name': 'Boswellia'}],
 'taxonomy': {'author': 'open tree of life project',
  'name': 'ott',
  'source': 'ott3.7draft3',
  'version': '3.7',
  'weburl': 'https://tree.opentreeoflife.org/about/taxonomy-version/ott3.7'},
 'unambiguous_names': ['Castilleja',
  'Orobanche',
  'Pedicularis',
  'Mimulus',
  'Erythranthe',
  'Aquilegia',
  'Quercus',
  'Boswellia'],
 'unmatched_names': []}

In [58]:
nwk = toytree.otol.induced_subtree(SUBTREE_SPP_LIST, insert_broken_nodes=True)
toytree.tree(nwk).draw();

ToytreeError: TNRS resolution has unresolved rows: 1 ambiguous, 1 unmatched.

In [57]:
toytree.otol.node_info('mrcaott1452ott33561')

[{'conflicts_with': {'ot_1417@Tr94055': ['Tn13857001'],
   'ot_1624@Tr85668': ['Tn12610356'],
   'ot_311@tree1': ['node60030',
    'node60060',
    'node60062',
    'node60090',
    'node60394',
    'node60440',
    'node60441',
    'node60755',
    'node60801',
    'node60802',
    'node60806',
    'node60814',
    'node60908',
    'node60909',
    'node60919',
    'node60925',
    'node60927',
    'node60960',
    'node60970',
    'node61052',
    'node61124',
    'node61125',
    'node61127',
    'node61128',
    'node61135',
    'node61137',
    'node61143',
    'node61147',
    'node61149',
    'node61151',
    'node61159',
    'node61170',
    'node61172',
    'node61180',
    'node61182',
    'node61184',
    'node61202',
    'node61221',
    'node61371',
    'node61372',
    'node61373',
    'node61374',
    'node61398',
    'node61399',
    'node62425',
    'node62427',
    'node62429',
    'node62430',
    'node62432',
    'node62446',
    'node62584',
    'node62586',
    'node62612',
    'node62624',
    'node62646',
    'node62658',
    'node62659',
    'node62661',
    'node62673',
    'node62674',
    'node62680',
    'node62684',
    'node62711',
    'node62713',
    'node62715',
    'node62719',
    'node62758',
    'node62780',
    'node62782',
    'node62792',
    'node62814',
    'node62830',
    'node62838',
    'node62840',
    'node62861',
    'node62891',
    'node62945',
    'node62949',
    'node62973',
    'node63069',
    'node63157',
    'node63158',
    'node63170',
    'node63206',
    'node63232',
    'node63234',
    'node63235',
    'node63258',
    'node63266',
    'node63267',
    'node63274',
    'node63276',
    'node63282'],
   'pg_1118@tree2226': ['node540308',
    'node540352',
    'node540376',
    'node540377',
    'node540389',
    'node540395',
    'node540396',
    'node540397',
    'node540398',
    'node540399',
    'node540403',
    'node540421'],
   'pg_2044@tree4212': ['node781294',
    'node781302',
    'node781336',
    'node781338',
    'node781390',
    'node781391',
    'node781401',
    'node781402',
    'node781404']},
  'node_id': 'mrcaott1452ott33561',
  'num_tips': 9853,
  'partial_path_of': {'ot_2304@tree2': 'node9551',
   'ot_2304@tree4': 'node20521',
   'ot_859@tree1': 'node179',
   'pg_713@tree1287': 'node435879'},
  'query': 'mrcaott1452ott33561',
  'source_id_map': {'ot_1417@Tr94055': {'git_sha': '',
    'study_id': 'ot_1417',
    'tree_id': 'Tr94055'},
   'ot_1624@Tr85668': {'git_sha': '',
    'study_id': 'ot_1624',
    'tree_id': 'Tr85668'},
   'ot_2089@Tr65393': {'git_sha': '',
    'study_id': 'ot_2089',
    'tree_id': 'Tr65393'},
   'ot_2116@tree1': {'git_sha': '', 'study_id': 'ot_2116', 'tree_id': 'tree1'},
   'ot_2304@tree2': {'git_sha': '', 'study_id': 'ot_2304', 'tree_id': 'tree2'},
   'ot_2304@tree4': {'git_sha': '', 'study_id': 'ot_2304', 'tree_id': 'tree4'},
   'ot_311@tree1': {'git_sha': '', 'study_id': 'ot_311', 'tree_id': 'tree1'},
   'ot_502@tree1': {'git_sha': '', 'study_id': 'ot_502', 'tree_id': 'tree1'},
   'ot_535@tree1': {'git_sha': '', 'study_id': 'ot_535', 'tree_id': 'tree1'},
   'ot_859@tree1': {'git_sha': '', 'study_id': 'ot_859', 'tree_id': 'tree1'},
   'pg_1118@tree2226': {'git_sha': '',
    'study_id': 'pg_1118',
    'tree_id': 'tree2226'},
   'pg_2044@tree4212': {'git_sha': '',
    'study_id': 'pg_2044',
    'tree_id': 'tree4212'},
   'pg_2539@tree6294': {'git_sha': '',
    'study_id': 'pg_2539',
    'tree_id': 'tree6294'},
   'pg_2820@tree6566': {'git_sha': '',
    'study_id': 'pg_2820',
    'tree_id': 'tree6566'},
   'pg_713@tree1287': {'git_sha': '',
    'study_id': 'pg_713',
    'tree_id': 'tree1287'}},
  'supported_by': {'ot_502@tree1': 'node1004',
   'pg_2539@tree6294': 'node1094779'},
  'synth_id': 'opentree16.1',
  'terminal': {'ot_2089@Tr65393': 'Tn10413075',
   'ot_2116@tree1': 'node173',
   'ot_535@tree1': 'ott648839',
   'pg_2820@tree6566': 'node1140548'}}]

In [46]:
nwk = toytree.otol.study_tree(study_id='pg_1944', tree_id='tree3959',)

In [49]:
toytree.tree(nwk).draw();

In [30]:
# toytree.otol.node_info(SUBTREE_GEN_LIST)

In [24]:
toytree.otol.supporting_studies()

ToytreeError: TNRS resolution has unresolved rows: 1 ambiguous, 1 unmatched.

In [ ]:
toytree.otol.study_id_from_doi("10.1002/ajb2.1019")

In [22]:
toytree.otol.study_tree("10.1002/ajb2.1019")

ToytreeError: OTOL request failed at endpoint 'https://api.opentreeoflife.org/v3/study/10.1002/ajb2.1019.tre/?tip_label=ot:originallabel'. status=404. error=404 Client Error: Not Found for url: https://api.opentreeoflife.org/v3/study/10.1002/ajb2.1019.tre/?tip_label=ot:originallabel. response_snippet='{"message": "Nothing found at this URL"}'

In [21]:
toytree.otol.synthetic_subtree(TAXON_LIST, full_json=True)

ToytreeError: TNRS resolution has unresolved rows: 1 ambiguous, 0 unmatched.

In [13]:
toytree.otol.mrca_taxon_id(TAXON_LIST[:2])

5263556

In [14]:
toytree.otol.taxon_info(5263556)

{'flags': [],
 'is_suppressed': False,
 'is_suppressed_from_synth': False,
 'name': 'Core_Lamiales',
 'ott_id': 5263556,
 'rank': 'no rank',
 'source': 'ott3.7draft3',
 'synonyms': [],
 'tax_sources': ['study713:13'],
 'unique_name': 'Core_Lamiales'}

In [19]:
toytree.otol.resolve_names(TAXON_LIST, context="Angiosperms", on_ambiguous="first")

,query,status,matched_name,ott_id,is_synonym,reason
0,Castilleja,matched,Castilleja,317400,False,ok
1,Castilleja campestris,matched,Castilleja campestris,83184,False,ok
2,Orobanche cumana,matched,Orobanche cumana,1010133,True,ok
3,Pedicularis anas,matched,Pedicularis anas,1032908,False,ok
4,Pedicularis groenlandica,matched,Pedicularis groenlandica,261492,False,ok
5,Mimulus guttatus,matched,Mimulus guttatus,504496,True,resolved_first_of_2
6,Aquilegia coerulea,matched,Aquilegia coerulea,192307,False,ok

In [17]:
toytree.otol.get_taxon_id_table(TAXON_LIST)

,query,status,matched_name,ott_id,is_synonym,reason
0,Castilleja,matched,Castilleja,317400,False,ok
1,Castilleja campestris,matched,Castilleja campestris,83184,False,ok
2,Orobanche cumana,unmatched,None,<NA>,None,no_match
3,Pedicularis anas,matched,Pedicularis anas,1032908,False,ok
4,Pedicularis groenlandica,matched,Pedicularis groenlandica,261492,False,ok
5,Mimulus guttatus,unmatched,None,<NA>,None,no_match
6,Aquilegia coerulea,matched,Aquilegia coerulea,192307,False,ok

In [67]:
toytree.otol.resolve_names(TAXON_LIST, include_synonyms=True)

,query,status,matched_name,ott_id,is_synonym,reason
0,Castilleja,matched,Castilleja,317400.0,False,ok
1,Castilleja campestris,matched,Castilleja campestris,83184.0,False,ok
2,Orobanche cumana,matched,Orobanche cumana,1010133.0,True,ok
3,Pedicularis anas,matched,Pedicularis anas,1032908.0,False,ok
4,Pedicularis groenlandica,matched,Pedicularis groenlandica,261492.0,False,ok
5,Mimulus guttatus,ambiguous,None,NaN,None,2_matches
6,Aquilegia coerulea,matched,Aquilegia coerulea,192307.0,False,ok

In [66]:
matched = toytree.otol.get_matched_names("Mimulus guttatus")
results = matched['results']
print(matched.keys())

dict_keys(['context', 'governing_code', 'includes_approximate_matches', 'includes_deprecated_taxa', 'includes_suppressed_names', 'matched_names', 'results', 'taxonomy', 'unambiguous_names', 'unmatched_names'])

In [4]:
print(results[0].keys())

dict_keys(['matches', 'name'])

matched['results'][0]['matches']

In [226]:
for i in results:
    print(i['name'], i['matches'])

Mimulus guttatus [{'is_approximate_match': False, 'is_synonym': True, 'matched_name': 'Mimulus guttatus', 'nomenclature_code': 'ICN', 'score': 1.0, 'search_string': 'mimulus guttatus', 'taxon': {'flags': [], 'is_suppressed': False, 'is_suppressed_from_synth': False, 'name': 'Erythranthe guttata', 'ott_id': 504496, 'rank': 'species', 'source': 'ott3.7draft3', 'synonyms': ['Mimulus clementinus', 'Mimulus equinus', 'Mimulus glabratus adscendens', 'Mimulus glabratus ascendens', 'Mimulus grandiflorus', 'Mimulus guttatus', 'Mimulus guttatus guttatus', 'Mimulus guttatus haidensis', 'Mimulus guttatus laxus', 'Mimulus guttatus lyratus', 'Mimulus guttatus puberulus', 'Mimulus guttatus subsp. guttatus', 'Mimulus hirsutus', 'Mimulus langsdorffii', 'Mimulus langsdorffii argutus', 'Mimulus langsdorffii guttatus', 'Mimulus langsdorffii minima', 'Mimulus langsdorffii platyphyllus', 'Mimulus laxus', 'Mimulus lyratus', 'Mimulus microphyllis', 'Mimulus paniculatus', 'Mimulus petiolaris', 'Mimulus prionophyllus', 'Mimulus puberulus', 'Mimulus rivularis'], 'tax_sources': ['ncbi:4155', 'gbif:7346102', 'irmng:10208223'], 'unique_name': 'Erythranthe guttata'}}, {'is_approximate_match': False, 'is_synonym': True, 'matched_name': 'Mimulus guttatus', 'nomenclature_code': 'ICN', 'score': 1.0, 'search_string': 'mimulus guttatus', 'taxon': {'flags': [], 'is_suppressed': False, 'is_suppressed_from_synth': False, 'name': 'Erythranthe lutea', 'ott_id': 662909, 'rank': 'species', 'source': 'ott3.7draft3', 'synonyms': ['Erythranthe lutea rivularis', 'Mimulus cupreus', 'Mimulus glabratus micranthus', 'Mimulus guttatus', 'Mimulus luteus', 'Mimulus luteus alpinus', 'Mimulus luteus cupreus', 'Mimulus luteus rivularis', 'Mimulus luteus youngeanus', 'Mimulus ocellatus', 'Mimulus perluteus', 'Mimulus punctatus'], 'tax_sources': ['ncbi:270988', 'gbif:7730307'], 'unique_name': 'Erythranthe lutea'}}]

In [216]:
i.keys()

dict_keys(['matches', 'name'])

In [203]:
toytree.otol.resolve_names(["Mimulus guttatus"])

              query     status matched_name ott_id is_synonym     reason
0  Mimulus guttatus  ambiguous         None   None       None  2_matches

In [190]:
DOI_Smith = "10.1002/ajb2.1019"
DOI_Zuntini = "..."

In [198]:
res = toytree.infer.phylomaker_subtree(TAXON_LIST, strict="warn")

WARNING: ambiguous/unmatched taxa present; using matched rows only.

In [200]:
res.report

,query,status,matched_name,ott_id,is_synonym,reason,query_normalized,source_context,used_in_tree,final_tip_label
0,Aquilegia coerulea,matched,Aquilegia coerulea,192307.0,False,ok,Aquilegia coerulea,None,True,Aquilegia_coerulea_ott192307
1,Castilleja,matched,Castilleja,317400.0,False,ok,Castilleja,None,False,NaN
2,Castilleja campestris,matched,Castilleja campestris,83184.0,False,ok,Castilleja campestris,None,True,Castilleja_campestris_ott83184
3,Mimulus guttatus,ambiguous,None,NaN,None,2_matches,Mimulus guttatus,None,False,None
4,Orobanche,matched,Orobanche,918756.0,False,ok,Orobanche,None,False,NaN
5,Pedicularis anas,matched,Pedicularis anas,1032908.0,False,ok,Pedicularis anas,None,True,Pedicularis_anas_ott1032908
6,Pedicularis groenlandica,matched,Pedicularis groenlandica,261492.0,False,ok,Pedicularis groenlandica,None,True,Pedicularis_groenlandica_ott261492

In [192]:
res.tree.draw();

## Find studies 
One of the core utilities of the Open Tree of Life is to store trees from published studies. These trees are the primary data from which the synthetic tree is constructed, and often contain additional data, such as branch lengths, that are not available in the synthetic tree. You can search for trees associated with a study by its DOI, or you can find the set of studies that are informative about a set of taxa by searching taxon names or IDs. 

### Find studies by DOI

In [145]:
# ...
columns = ["ot:studyId", "o

{"matched_studies": [{"ot:studyId": "ot_1974", "ot:studyPublicationReference": "Smith, S. A., & Brown, J. W. (2018). Constructing a broadly inclusive seed plant phylogeny. American Journal of Botany, 105(3), 302\u2013314. doi:10.1002/ajb2.1019\n", "ot:curatorName": ["Brian O&#x27;Meara"], "ot:studyYear": 2018, "ot:focalCladeOTTTaxonName": "", "ot:dataDeposit": "", "ot:studyPublication": "http://dx.doi.org/10.1002/ajb2.1019", "ot:tag": []}]}

### Find studies informative about a set of taxa

In [12]:
tree = toytree.rtree.unittree(20)
tree[0].name = "XXXXXXXXXXXXXXXXXXXXXX"

In [14]:
tree.draw(layout='d');

In [16]:
import toyplot

c = toyplot.Canvas()
a = c.cartesian()
_, _, m = tree.draw(axes=a, )

In [64]:
c = toyplot.Canvas()
a0 = c.cartesian()
tree.draw(axes=a0)
a0.y.show = False
tree.annotate.add_tip_text(a0)

In [57]:
c, a, m = tree.draw(scale_bar=True);

In [45]:
c, a, m = tree.draw();
tree.annotate.add_axes_scale_bar(a);